name: 'zbctl'
description: 'Run zbctl commands in your actions'
inputs:
  version:
    description: 'Which version of zbctl should be used.'
    required: true
  command:
    description: 'zbctl command to run, for example "deploy process.bpmn".'
    required: true
outputs:
  result:
    description: 'JSON output of zbctl'
runs:
  using: 'node12'
  main: 'dist/index.js'